//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thulyadb.Dynamic
{
    using System;
    using CqlSharp;
    using CqlSharp.Linq;
    using CqlSharp.Serialization;

    public class TLY_UserHomeStats
    {
        [CqlKey]
        public System.String UserId { get; set; }

        public System.Int64 HomeProfViewsSinceLastUpdate { get; set; }

        public System.Int64 HomeProfViewsTotal { get; set; }

        public System.Int64 RowTimeStamp { get; set; }

    }

    public partial class ThulyadbContext : CqlContext
    {
        public CqlTable<TLY_UserHomeStats> TLY_UserHomeStatsTable { get; set; }

        public ThulyadbContext(bool initializeTables = true) :
            base(initializeTables)
        {
        }

        public ThulyadbContext(string connectionString, bool initializeTables = true) :
            base(connectionString, initializeTables)
        {
        }
    }
}
